In [63]:
###################################
#                                 #
#  Result_tables.ipynb            #
#  Akhil Garg, akhil@akhilgarg.ca #
#  Created 2021-07-30             #
#                                 #
###################################

import numpy  as np
import pandas as pd
from tableone import TableOne 
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

CTU_data   = pd.read_excel('CTU_data 2021-05-27.xlsx',index_col=0)
date_frame = pd.read_excel('Daily CTU Census 2021-05-28.xlsx')
diagnoses  = pd.read_excel('Discharge diagnoses.xlsx')

## Patient demographic data

In [43]:
CTU_data

,ConsultRequestDateTime,ADMISSION_DATE_TIME,DISCHARGE_DATE_TIME,SEX,AGE,CCI,daily_admits,Drip,G_exists,consult_duration_hours,Death,Readmission,LOS
0,2015-07-01 13:02:00,2015-07-01 16:58:00,2015-07-03 16:57:00,Female,86.166320,2,7,0,0,3.933333,False,False,1.999306
1,2015-07-01 16:09:00,2015-07-01 18:57:00,2015-08-01 11:38:00,Male,66.667917,2,7,0,0,2.800000,False,False,30.695139
2,2015-07-01 15:57:00,2015-07-01 20:01:00,2015-07-08 09:44:00,Female,71.095436,1,7,0,0,4.066667,False,False,6.571528
3,2015-07-01 18:51:00,2015-07-01 22:36:00,2015-07-07 14:35:00,Male,71.117648,0,7,0,0,3.750000,False,False,5.665972
4,2015-07-01 12:48:00,2015-07-01 23:00:00,2015-07-04 07:07:00,Female,43.531393,0,7,0,0,10.200000,False,False,2.338194
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19137,2020-03-14 07:07:00,2020-03-14 13:43:00,2020-03-20 15:17:00,Female,80.894717,1,11,1,1,6.600000,False,False,6.065278
19138,2020-03-14 12:00:00,2020-03-14 16:47:00,2020-03-19 16:08:00,Female,87.960820,1,11,1,1,4.783333,False,False,4.972917
19139,2020-03-14 13:17:00,2020-03-14 19:20:00,2020-03-25 13:03:00,Male,67.046043,2,11,1,1,6.050000,False,False,10.738194
19140,2020-03-14 13:39:00,2020-03-14 22:10:00,2020-04-01 08:52:00,Female,91.084722,1,11,1,1,8.516667,False,False,17.445833
19141,2020-03-14 16:47:00,2020-03-14 22:39:00,2020-03-18 14:01:00,Female,34.739572,1,11,1,1,5.866667,False,False,3.640278

In [46]:
columns = ['AGE','SEX','LOS','daily_admits','consult_duration_hours','CCI','Death','Drip','Readmission']

table1 = TableOne(CTU_data, columns=columns,groupby='Drip',pval=True)
print(table1.tabulate(tablefmt='fancy_grid'))

╒═══════════════════════════════════╤════════╤═══════════╤══════════════╤══════════════╤═════════════╤═══════════╕
│                                   │        │ Missing   │ Overall      │ 0            │ 1           │ P-Value   │
╞═══════════════════════════════════╪════════╪═══════════╪══════════════╪══════════════╪═════════════╪═══════════╡
│ n                                 │        │           │ 18991        │ 11585        │ 7406        │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ AGE, mean (SD)                    │        │ 0         │ 67.8 (18.0)  │ 67.6 (18.1)  │ 68.1 (17.9) │ 0.092     │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ SEX, n (%)                        │ Female │ 0         │ 9713 (51.1)  │ 5940 (51.3)  │ 3773 (50.9) │ 0.670     │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ Male   │           │ 9278 (48.9)  │ 5645 (48.7)  │ 3633 (49.1) │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ LOS, mean (SD)                    │        │ 0         │ 7.3 (9.6)    │ 7.2 (9.4)    │ 7.5 (9.8)   │ 0.040     │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ daily_admits, n (%)               │ 10     │ 0         │ 1860 (9.8)   │ 1313 (11.3)  │ 547 (7.4)   │ <0.001    │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 11     │           │ 2175 (11.5)  │ 1365 (11.8)  │ 810 (10.9)  │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 12     │           │ 1989 (10.5)  │ 1152 (9.9)   │ 837 (11.3)  │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 13     │           │ 1988 (10.5)  │ 1194 (10.3)  │ 794 (10.7)  │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 14     │           │ 1668 (8.8)   │ 923 (8.0)    │ 745 (10.1)  │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 15     │           │ 1347 (7.1)   │ 702 (6.1)    │ 645 (8.7)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 16     │           │ 1154 (6.1)   │ 498 (4.3)    │ 656 (8.9)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 17     │           │ 779 (4.1)    │ 354 (3.1)    │ 425 (5.7)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 18     │           │ 591 (3.1)    │ 269 (2.3)    │ 322 (4.3)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 19     │           │ 418 (2.2)    │ 114 (1.0)    │ 304 (4.1)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 2      │           │ 2 (0.0)      │ 2 (0.0)      │             │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 20     │           │ 160 (0.8)    │ 80 (0.7)     │ 80 (1.1)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 21     │           │ 231 (1.2)    │ 84 (0.7)     │ 147 (2.0)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 22     │           │ 22 (0.1)     │              │ 22 (0.3)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 23     │           │ 46 (0.2)     │ 23 (0.2)     │ 23 (0.3)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 24     │           │ 24 (0.1)     │ 24 (0.2)     │             │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 26     │           │ 26 (0.1)     │              │ 26 (0.4)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 3      │           │ 37 (0.2)     │ 34 (0.3)     │ 3 (0.0)     │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 4      │           │ 60 (0.3)     │ 56 (0.5)     │ 4 (0.1)     │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 5      │           │ 240 (1.3)    │ 185 (1.6)    │ 55 (0.7)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 6      │           │ 489 (2.6)    │ 393 (3.4)    │ 96 (1.3)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 7      │           │ 814 (4.3)    │ 660 (5.7)    │ 154 (2.1)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 8      │           │ 1321 (7.0)   │ 1034 (8.9)   │ 287 (3.9)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 9      │           │ 1550 (8.2)   │ 1126 (9.7)   │ 424 (5.7)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ consult_duration_hours, mean (SD) │        │ 0         │ 4.9 (2.5)    │ 5.0 (2.5)    │ 4.8 (2.4)   │ <0.001    │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ CCI, n (%)                        │ 0      │ 0         │ 8425 (44.4)  │ 5125 (44.2)  │ 3300 (44.6) │ 0.010     │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 1      │           │ 5429 (28.6)  │ 3340 (28.8)  │ 2089 (28.2) │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 10     │           │ 4 (0.0)      │              │ 4 (0.1)     │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 2      │           │ 2884 (15.2)  │ 1703 (14.7)  │ 1181 (15.9) │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 3      │           │ 1305 (6.9)   │ 828 (7.1)    │ 477 (6.4)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 4      │           │ 592 (3.1)    │ 362 (3.1)    │ 230 (3.1)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 5      │           │ 187 (1.0)    │ 115 (1.0)    │ 72 (1.0)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 6      │           │ 91 (0.5)     │ 65 (0.6)     │ 26 (0.4)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 7      │           │ 45 (0.2)     │ 32 (0.3)     │ 13 (0.2)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 8      │           │ 25 (0.1)     │ 12 (0.1)     │ 13 (0.2)    │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ 9      │           │ 4 (0.0)      │ 3 (0.0)      │ 1 (0.0)     │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ Death, n (%)                      │ False  │ 0         │ 17755 (93.5) │ 10842 (93.6) │ 6913 (93.3) │ 0.527     │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ True   │           │ 1236 (6.5)   │ 743 (6.4)    │ 493 (6.7)   │           │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│ Readmission, n (%)                │ False  │ 0         │ 16669 (87.8) │ 10187 (87.9) │ 6482 (87.5) │ 0.414     │
├───────────────────────────────────┼────────┼───────────┼──────────────┼──────────────┼─────────────┼───────────┤
│                                   │ True   │           │ 2322 (12.2)  │ 1398 (12.1)  │ 924 (12.5)  │           │
╘═══════════════════════════════════╧════════╧═══════════╧══════════════╧══════════════╧═════════════╧═══════════╛

In [54]:
CTU_data.groupby(['Drip']).median()['CCI']

Drip
0    1
1    1
Name: CCI, dtype: int64

## Discharge diagnosis data

In [64]:
diagnoses

,EncounterNumber,DiagnosisCIHIValue,Admit date,Drip?,First letter
0,1159005795,J81,2015-07-01 01:05:00,0,J
1,1159005801,J441,2015-07-01 01:44:00,0,J
2,1159005802,I500,2015-07-01 02:23:00,0,I
3,1159005804,E1010,2015-07-01 04:00:00,0,E
4,1159005805,R53,2015-07-01 04:10:00,0,R
...,...,...,...,...,...
25527,1209005176,R060,2020-06-30 19:24:00,1,R
25528,1209005178,M6289,2020-06-30 20:17:00,1,M
25529,1209005180,K922,2020-06-30 21:39:00,1,K
25530,1209005182,L0311,2020-06-30 22:25:00,1,L
25531,1209005184,J189,2020-06-30 23:17:00,1,J

In [103]:
ICD_dictionary = {
    'A':'infectious',
    'C':'neoplasms',
    'D':'blood and immune',
    'E':'endocrine and metabolic',
    'F':'mentall, behavioural, neurodevelopmental',
    'G':'nervous system',
    'H':'eye',
    'I':'circulatory',
    'J':'respiratory',
    'K':'GI',
    'L':'skin/soft tissue',
    'M':'MSK/connective tissue',
    'N':'GU',
    'O':'pregnancy',
    'P':'perinatal',
    'Q':'congenital',
    'R':'abnormal clinical/labs',
    'S':'poisoning',
    'U':'special codes',
    'V':'external causes',
    'Z':'healthcare contact'
}
ICD_dictionary

{'A': 'infectious',
 'C': 'neoplasms',
 'D': 'blood and immune',
 'E': 'endocrine and metabolic',
 'F': 'mentall, behavioural, neurodevelopmental',
 'G': 'nervous system',
 'H': 'eye',
 'I': 'circulatory',
 'J': 'respiratory',
 'K': 'GI',
 'L': 'skin/soft tissue',
 'M': 'MSK/connective tissue',
 'N': 'GU',
 'O': 'pregnancy',
 'P': 'perinatal',
 'Q': 'congenital',
 'R': 'abnormal clinical/labs',
 'S': 'poisoning',
 'U': 'special codes',
 'V': 'external causes',
 'Z': 'healthcare contact'}

In [74]:
diagnoses['ICD category'] = diagnoses['First letter'].map(ICD_dictionary)
diagnoses

,EncounterNumber,DiagnosisCIHIValue,Admit date,Drip?,First letter,ICD category
0,1159005795,J81,2015-07-01 01:05:00,0,J,respiratory
1,1159005801,J441,2015-07-01 01:44:00,0,J,respiratory
2,1159005802,I500,2015-07-01 02:23:00,0,I,circulatory
3,1159005804,E1010,2015-07-01 04:00:00,0,E,endocrine and metabolic diseases
4,1159005805,R53,2015-07-01 04:10:00,0,R,abnormal clinical/labs
...,...,...,...,...,...,...
25527,1209005176,R060,2020-06-30 19:24:00,1,R,abnormal clinical/labs
25528,1209005178,M6289,2020-06-30 20:17:00,1,M,MSK/connective tissue
25529,1209005180,K922,2020-06-30 21:39:00,1,K,GI
25530,1209005182,L0311,2020-06-30 22:25:00,1,L,skin/soft tissue
25531,1209005184,J189,2020-06-30 23:17:00,1,J,respiratory

In [87]:
group = diagnoses.groupby('Drip?')
group['ICD category'].value_counts(normalize=True)

Drip?  ICD category
0      respiratory                                 0.243571
       GI                                          0.156714
       circulatory                                 0.099357
       GU                                          0.093143
       endocrine and metabolic diseases            0.080214
       infectious diseases                         0.067714
       abnormal clinical/labs                      0.061643
       neoplasms                                   0.058500
       mentall, behavioural, neurodevelopmental    0.032429
       MSK/connective tissue                       0.026857
       skin/soft tissue                            0.026714
       blood and immune                            0.023714
       nervous system                              0.013214
       poisoning                                   0.007643
       healthcare contact                          0.007214
       eye                                         0.001000
       pregnancy                                   0.000214
       congenital                                  0.000143
1      respiratory                                 0.240586
       GI                                          0.149296
       circulatory                                 0.097185
       endocrine and metabolic diseases            0.083967
       GU                                          0.081305
       abnormal clinical/labs                      0.071795
       infectious diseases                         0.063427
       neoplasms                                   0.056961
       mentall, behavioural, neurodevelopmental    0.037752
       skin/soft tissue                            0.032617
       blood and immune                            0.030430
       MSK/connective tissue                       0.024344
       nervous system                              0.010841
       poisoning                                   0.009319
       healthcare contact                          0.008273
       eye                                         0.000761
       special codes                               0.000475
       pregnancy                                   0.000380
       congenital                                  0.000285
Name: ICD category, dtype: float64

In [101]:
diagnoses[diagnoses['Drip?']==0]['DiagnosisCIHIValue'].value_counts(normalize=True).head(10)

J441     0.058194
N390     0.040694
J189     0.037881
J440     0.036646
I500     0.031499
N179     0.025460
J690     0.021548
K922     0.019901
L0311    0.015646
E1010    0.012764
Name: DiagnosisCIHIValue, dtype: float64

In [102]:
diagnoses[diagnoses['Drip?']==1]['DiagnosisCIHIValue'].value_counts(normalize=True).head(10)

J441     0.059763
J189     0.043887
I500     0.035584
N390     0.034398
J440     0.029288
N179     0.024818
J690     0.024544
L0311    0.018704
K922     0.018522
E1010    0.012591
Name: DiagnosisCIHIValue, dtype: float64

## Hospital flow data